[package]
name = "w2"
version = "0.1.0"
edition = "2021"
default-run = "w2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.20.0"
image = "0.25.1"
rand = "0.8.5"
rand_distr = "0.4.3"
thiserror = "1.0.63"
